# conda env create --file environment.yml
name: 'hugging'
channels:
  - conda-forge
dependencies:
  - pip
  
  ## uncomment for use with Jupyter
  - ipykernel
  - ipywidgets
  - nb_conda_kernels
  - nbformat

  ## PyPI packages
  - pip: 
    - tensorflow-cpu
    - transformers
    - evaluate
    - scikit-learn
    - zstandard
    - python-dotenv
    - faiss-cpu
    - huggingface-hub
    - datasets
    - seqeval

